### Notas de Daniel Salgado (CNS - IPICyT) para el curso Introducción a la programación y al aprendizaje de máquinas con Python (2020)

# Pimp my ride

En esta sección veremos algunas herramientas extras, útiles para trabajar con Python

### Numpy

Numpy es una biblioteca que provee herramientas muy útiles para cómputo científico. Entre otras cosas, contiene:

* extensión para operaciones de alto desempeño con arreglos multidimensionales
* en general, sus operaciones son más eficientes (muchas vienen de funciones compiladas en c = bajo nivel). 
* maneja contenedores utilizando de forma eficiente la memoria: espacios contiguos de memoria y por lo general más pequeños que un contenedor común de Python (así que es más rápido).
* está diseñado/pensado para cómputo científico (resulta conveniente). En particular, incluye algoritmos comúnes para operar sobre arreglos.

http://www.numpy.org/

Una característica clave de numpy es la existencia de sus arreglos multidimensionales, los cuales son contenedores rápidos y flexibles para datos. Estos arreglos son de un solo tipo de variable (necesario para poder ser eficientes).

In [1]:
import numpy as np
# Es posible convertir un contenedor en un arreglo de numpy
lista = [i for i in range(100)]
arrnp1 = np.array(lista)
print("arrnp1 es del tipo {}, y tiene una longitud de {} y una forma de {}".format(type(arrnp1), arrnp1.size, arrnp1.shape))

arrnp1 es del tipo <class 'numpy.ndarray'>, y tiene una longitud de 100 y una forma de (100,)


In [2]:
# También se puede crear directamente desde numpy
# Arreglo de 1's
arrnp2 = np.ones((3,4))
print(arrnp2)
print("arrnp2 tiene una longitud de {} y una forma de {}".format(arrnp2.size, arrnp2.shape))

# Arreglo de 0's
arrnp3 = np.zeros((3,4))
print("\n****\n")
print(arrnp3)

# Arreglo de valore "aleatorios"
arrnp4 = np.random.random((3,4))
print("\n****\n")
print(arrnp4)

# Arreglo vacío
arrnp5 = np.empty((3,4))
print("\n****\n")
print(arrnp5)

# Arreglo lleno de pi's
arrnp6 = np.full((3,4),np.pi)
print("\n****\n")
print(arrnp6)



[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
arrnp2 tiene una longitud de 12 y una forma de (3, 4)

****

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

****

[[0.11213403 0.39127647 0.99001831 0.84441188]
 [0.29836219 0.87540236 0.98443461 0.88825949]
 [0.97907209 0.23744347 0.24769605 0.34261775]]

****

[[0.11213403 0.39127647 0.99001831 0.84441188]
 [0.29836219 0.87540236 0.98443461 0.88825949]
 [0.97907209 0.23744347 0.24769605 0.34261775]]

****

[[3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265]]


__Ejercicio__ Utilizando numpy, crea una matriz de 5x5 cuyos elementos sean números "aleatorios" entre 0 y 1 (revisa función random de numpy: https://docs.scipy.org/doc/numpy-1.16.0/reference/routines.random.html).

In [1]:
# Tu respuesta aquí
#include <numpy>
import numpy as np

arr = np.random.random((5,5))
print(arr)

[[0.22326974 0.24677139 0.29456882 0.32557161 0.69375284]
 [0.400723   0.20334895 0.48483065 0.96436405 0.69638348]
 [0.92210777 0.61210333 0.55082869 0.39704124 0.02796054]
 [0.78348055 0.68121374 0.02396359 0.92332611 0.94864949]
 [0.31394071 0.18500479 0.38123722 0.21860507 0.6858383 ]]


Estos arreglos pueden ser n-dimensionales. Las dimensiones de un arreglo se pueden consultar mediante arreglo.ndim  

Cada dimensión tiene un tamaño, que corresponde al número de elementos que componen a esa dimensión. Por ejemplo, np.ones((3,4,2)) tiene 3 dimensiones, donde la primera dimensión tienen una longitudo de 3, la segunda tiene una longitud de 4 y la tercera tienen una longitud de 2.  

Para acceder a los elementos del arreglo, se pueden utilizar índices (y por tanto también slicing).

In [33]:
# Arreglo de 3x3: 2 dimensiones, cada una de longitud 3
arreglo = np.array([[1.5, 2.5, 3.5],[2.1, 3.1, 4.1],[0.7, 1.7, 2.7]])
print(arreglo.shape)
print(arreglo)
print("\n****\n")
print(arreglo[0])
print("\n****\n")
print(arreglo[1])
print("\n****\n")
print(arreglo[2])

# Para acceder al otro eje, se puede utilizar una coma para separar el índice
print("\n****\n")
print(arreglo[:,0])
print("\n****\n")
print(arreglo[:,1])
print("\n****\n")
print(arreglo[:,2])

(3, 3)
[[1.5 2.5 3.5]
 [2.1 3.1 4.1]
 [0.7 1.7 2.7]]

****

[1.5 2.5 3.5]

****

[2.1 3.1 4.1]

****

[0.7 1.7 2.7]

****

[1.5 2.1 0.7]

****

[2.5 3.1 1.7]

****

[3.5 4.1 2.7]


__Ejercicio__ Modifica la matriz creada en el ejercicio anterior de la siguiente forma: suma 1.0 a las columnas pares y suma 2.0 a las filas impares.

In [4]:
# Tu respuesta aquí
arrcomplete = arr[0:arr.size:2and]+1.+arr[1:arr.size+1:2]+2.

ValueError: operands could not be broadcast together with shapes (3,5) (2,5) 

Un ejemplo sobre la velocidad de numpy

In [11]:
# Utilizando la magic function timeit, compara el tiempo que lleva ejecutar las siguientes dos versiones 
# Elevar al cuadrado números en lista, versión normal Python
lini = [i for i in range(1000)]    # List comprehension para crear lista inicial
lno = [i**2 for i in lini]  # List comprehension para elevar al cuadrado cada elemento

# Utiliza timeit aquí para medir el tiempo que toma elevar al cuadrada cada elemento,
# utilizando una comprensión de lista
%timeit [i**2 for i in lini]

# Elevar al cuadrado números dentro de arreglo numpy (mismo número de elementos que lista anterior)
import numpy as np           # Importo el módulo numpy con el nombre np
lini_nu = np.arange(1000)    # Creo un arreglo en numpy  
lfin_nu = lini_nu**2         # Elevo al cuadrado cada elemento

# Utiliza timeit aquí para medir el tiempo que toma la misma operación,
# pero utilizando operaciones con numpy
%timeit lini_nu**2


265 µs ± 1.89 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
1.3 µs ± 12.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


Como intentan mostrar los ejemplos anteriores, numpy me permite manejar arreglos multidimensionales de forma sencilla. 

In [42]:
# Por ejemplo:
a = np.arange(valini,valfin,tamaño paso)     # Genero números en un rango, y espaciados como yo quiera
print(a)
print("\n****\n")
b = np.linspace(valini,valfin,numero de puntos)   # Hago una partición de N elementos (20 en este caso), dentro de un rango
print(b)

[ 5.   6.2  7.4  8.6  9.8 11.  12.2 13.4 14.6 15.8 17.  18.2 19.4 20.6
 21.8 23.  24.2 25.4 26.6 27.8 29.  30.2 31.4 32.6 33.8 35.  36.2 37.4
 38.6 39.8 41.  42.2 43.4 44.6 45.8 47.  48.2 49.4 50.6]

****

[0.         0.26315789 0.52631579 0.78947368 1.05263158 1.31578947
 1.57894737 1.84210526 2.10526316 2.36842105 2.63157895 2.89473684
 3.15789474 3.42105263 3.68421053 3.94736842 4.21052632 4.47368421
 4.73684211 5.        ]


__Ejemplo__ Crea un programa que genere 100 puntos aleatorios en un espacio 3d, y calcula la distancia promedio de estos puntos con respecto al punto (1,0,0). Compara el tiempo que toma calcular las distancias con numpy contra una forma más tradicional.

In [17]:
# observar funciones de numpy random.random y linalg.norm
import numpy as np
from random import random as rconv

def funnp():
    pos = np.random.random((100,3)) # <- 100 elementos con 3 componentes "aleatorias"
    vec = np.array([1,0,0])
    pos -= vec
    lisdis = []
    for i in range(100):
        lisdis.append(np.linalg.norm(pos[i]))
    return lisdis

def funtrad():
    listav = []
    for i in range(100):
        vec = []
        for j in range(3):
            vec.append(rconv())
        listav.append(vec)
    for vector in listav:
        vector[0] -= 1.0
        vector[1] -= 0.0
        vector[2] -= 0.0
    lisdis = []
    for vector in listav:
        dist = 0.0
        for i in range(3):
            dist += vector[i]*vector[i]
        lisdis.append(np.sqrt(dist))
    return lisdis
    

%timeit funnp()
%timeit funtrad()

[0.8949286603738611, 1.1432495179651812, 0.9467181541876185, 0.8283139134586555, 1.0999942280989885, 1.4122980915875374, 0.9734690771272944, 1.2635016492838587, 0.9940505518773041, 0.4526823736618424]
[1.1619617435922693, 0.6883647059242095, 0.8569074996460969, 1.439527016657754, 1.0834774653345542, 0.6413061949943802, 1.1518252609412438, 1.2148611855478213, 0.8296804994741308, 1.3298409010817938]
572 µs ± 7.96 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
246 µs ± 897 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [21]:
import random
with open("Datos_locos.dat", "w") as fout:
    fout.write("Un encabezado X\n")
    fout.write("Algunas especificaciones mega-útiles\n")
    for i in range(10000):
        fout.write("{:.9f}\t{:.9f}\t{:.9f}\n".format(random.random(),random.random(),random.random()))

# Es muy sencillo importar archivos con datos numéricos, y manipularlos
# En linux:
!head -3 ./Datos_locos.dat # Despliego primeras 5 líneas de archivo
!tail -1 ./Datos_locos.dat # Despliego primeras 5 líneas de archivo

# Ahora utilizo numpy para importarlo y sacarle información
dat1 = np.loadtxt("Datos_locos.dat", skiprows=2) # 2 líneas texto
print("\n")
print("El valor promedio de la primera columna: {}".format(np.average(dat1[:,0]))) # Obtengo promedio de la primera columna

# Ahora imprime el valor promedio de la 2da y 3ra columna, junto con su desviación estándar
# aquí tu código
print("El valor promedio de la segunda columna: {} +- {}".format(np.average(dat1[:,1]), np.std(dat1[:,1])))
print("El valor promedio de la tercera columna: {} +- {}".format(np.average(dat1[:,2]), np.std(dat1[:,2])))

Un encabezado X
Algunas especificaciones mega-útiles
0.907088484	0.339993630	0.499907169
0.026791064	0.777656056	0.864506894


El valor promedio de la primera columna: 0.5032929888126
El valor promedio de la segunda columna: 0.4968440681894001 +- 0.28783934871296607
El valor promedio de la tercera columna: 0.5003817972412999 +- 0.2866634578266016


__Ejercicio__ Contesta las siguientes dos preguntas, tomando en cuenta el siguiente arreglo de numpy:

a = numpy.linspace(0,4,12).reshape(3,2,2)

_¿Cuántas dimensiones tiene el arreglo?_

_¿Qué tamaño tiene la última dimensión del arreglo?_


In [1]:
# Tu respuesta aquí


__Ejercicio__ Utilizando numpy, crea la matriz identidad de 4x4

In [22]:
# Tu respuesta aquí


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


__Ejercicio__ Utilizando numpy, crea una matriz diagonal con los elementos 5, 6, 7 y 8

In [23]:
# Tu respuesta aquí


[[5 0 0 0]
 [0 6 0 0]
 [0 0 7 0]
 [0 0 0 8]]


__Ejercicio__ Utilizando numpy, crea un programa que calcule el ángulo que hay entre dos vectores (recordar definición geométrica del producto punto: https://es.wikipedia.org/wiki/Producto_escalar)

In [32]:
# Tu respuesta aquí


0 90.0


__Ejercicio__ Utilizando numpy y los arreglos definidos en la celda de abajo, a) suma el vector r a cada fila de la matriz, y b) suma el vector c a cada columna de la matriz.

In [5]:
# Definición de arreglos
import numpy as np

mat = np.arange(12).reshape((4,3))
r = np.array(range(1,4))
c = np.array([1,0,0,0])

print(mat)
print(r)
print(c)

# a) Tu respuesta aquí


# b) Tu respuesta aquí


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[1 2 3]
[1 0 0 0]
[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]
 [10 12 14]]
[[ 2  4  6]
 [ 4  6  8]
 [ 7  9 11]
 [10 12 14]]
